version: '3.9'
services:
  db-mysql:
    image: mysql:5.7.41
    container_name: fullstack
    restart: always
    environment:
      MYSQL_DATABASE: nodejs_backend
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USERNAME: root
      MYSQL_USER_PORT: 3306
      MYSQL_USER_HOST: localhost
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
